INSERT INTO  Language 
VALUES ('aa', 'Afar');
INSERT INTO  Language 
VALUES ('ab', 'Abkhazian');
INSERT INTO  Language 
VALUES ('ae', 'Avestan');
INSERT INTO  Language 
VALUES ('af', 'Afrikaans');
INSERT INTO  Language 
VALUES ('ak', 'Akan');
INSERT INTO  Language 
VALUES ('am', 'Amharic');
INSERT INTO  Language 
VALUES ('an', 'Aragonese');
INSERT INTO  Language 
VALUES ('ar', 'Arabic');
INSERT INTO  Language 
VALUES ('as', 'Assamese');
INSERT INTO  Language 
VALUES ('av', 'Avaric');
INSERT INTO  Language 
VALUES ('ay', 'Aymara');
INSERT INTO  Language 
VALUES ('az', 'Azerbaijani');
INSERT INTO  Language 
VALUES ('ba', 'Bashkir');
INSERT INTO  Language 
VALUES ('be', 'Belarusian');
INSERT INTO  Language 
VALUES ('bg', 'Bulgarian');
INSERT INTO  Language 
VALUES ('bh', 'Bihari');
INSERT INTO  Language 
VALUES ('bi', 'Bislama');
INSERT INTO  Language 
VALUES ('bm', 'Bambara');
INSERT INTO  Language 
VALUES ('bn', 'Bengali');
INSERT INTO  Language 
VALUES ('bo', 'Tibetan');
INSERT INTO  Language 
VALUES ('br', 'Breton');
INSERT INTO  Language 
VALUES ('bs', 'Bosnian');
INSERT INTO  Language 
VALUES ('ca', 'Catalan');
INSERT INTO  Language 
VALUES ('ce', 'Chechen');
INSERT INTO  Language 
VALUES ('ch', 'Chamorro');
INSERT INTO  Language 
VALUES ('co', 'Corsican');
INSERT INTO  Language 
VALUES ('cr', 'Cree');
INSERT INTO  Language 
VALUES ('cs', 'Czech');
INSERT INTO  Language 
VALUES ('cu', 'Church Slavic');
INSERT INTO  Language 
VALUES ('cv', 'Chuvash');
INSERT INTO  Language 
VALUES ('cy', 'Welsh');
INSERT INTO  Language 
VALUES ('da', 'Danish');
INSERT INTO  Language 
VALUES ('de', 'German');
INSERT INTO  Language 
VALUES ('dv', 'Divehi');
INSERT INTO  Language 
VALUES ('dz', 'Dzongkha');
INSERT INTO  Language 
VALUES ('ee', 'Ewe');
INSERT INTO  Language 
VALUES ('el', 'Modern Greek');
INSERT INTO  Language 
VALUES ('en', 'English');
INSERT INTO  Language 
VALUES ('eo', 'Esperanto');
INSERT INTO  Language 
VALUES ('es', 'Spanish');
INSERT INTO  Language 
VALUES ('et', 'Estonian');
INSERT INTO  Language 
VALUES ('eu', 'Basque');
INSERT INTO  Language 
VALUES ('fa', 'Persian');
INSERT INTO  Language 
VALUES ('ff', 'Fulah');
INSERT INTO  Language 
VALUES ('fi', 'Finnish');
INSERT INTO  Language 
VALUES ('fj', 'Fijian');
INSERT INTO  Language 
VALUES ('fo', 'Faroese');
INSERT INTO  Language 
VALUES ('fr', 'French');
INSERT INTO  Language 
VALUES ('fy', 'Western Frisian');
INSERT INTO  Language 
VALUES ('ga', 'Irish');
INSERT INTO  Language 
VALUES ('gd', 'Gaelic');
INSERT INTO  Language 
VALUES ('gl', 'Galician');
INSERT INTO  Language 
VALUES ('gn', 'Guarani');
INSERT INTO  Language 
VALUES ('gu', 'Gujarati');
INSERT INTO  Language 
VALUES ('gv', 'Manx');
INSERT INTO  Language 
VALUES ('ha', 'Hausa');
INSERT INTO  Language 
VALUES ('he', 'Hebrew');
INSERT INTO  Language 
VALUES ('hi', 'Hindi');
INSERT INTO  Language 
VALUES ('ho', 'Hiri Motu');
INSERT INTO  Language 
VALUES ('hr', 'Croatian');
INSERT INTO  Language 
VALUES ('ht', 'Haitian');
INSERT INTO  Language 
VALUES ('hu', 'Hungarian');
INSERT INTO  Language 
VALUES ('hy', 'Armenian');
INSERT INTO  Language 
VALUES ('hz', 'Herero');
INSERT INTO  Language 
VALUES ('ia', 'Interlingua');
INSERT INTO  Language 
VALUES ('id', 'Indonesian');
INSERT INTO  Language 
VALUES ('ie', 'Interlingue');
INSERT INTO  Language 
VALUES ('ig', 'Igbo');
INSERT INTO  Language 
VALUES ('ii', 'Sichuan Yi');
INSERT INTO  Language 
VALUES ('ik', 'Inupiaq');
INSERT INTO  Language 
VALUES ('io', 'Ido');
INSERT INTO  Language 
VALUES ('is', 'Icelandic');
INSERT INTO  Language 
VALUES ('it', 'Italian');
INSERT INTO  Language 
VALUES ('iu', 'Inuktitut');
INSERT INTO  Language 
VALUES ('ja', 'Japanese');
INSERT INTO  Language 
VALUES ('jv', 'Javanese');
INSERT INTO  Language 
VALUES ('ka', 'Georgian');
INSERT INTO  Language 
VALUES ('kg', 'Kongo');
INSERT INTO  Language 
VALUES ('ki', 'Kikuyu; Gikuyu');
INSERT INTO  Language 
VALUES ('kj', 'Kuanyama; Kwanyama');
INSERT INTO  Language 
VALUES ('kk', 'Kazakh');
INSERT INTO  Language 
VALUES ('kl', 'Kalaallisut; Greenlandic');
INSERT INTO  Language 
VALUES ('km', 'Central Khmer');
INSERT INTO  Language 
VALUES ('kn', 'Kannada');
INSERT INTO  Language 
VALUES ('ko', 'Korean');
INSERT INTO  Language 
VALUES ('kr', 'Kanuri');
INSERT INTO  Language 
VALUES ('ks', 'Kashmiri');
INSERT INTO  Language 
VALUES ('ku', 'Kurdish');
INSERT INTO  Language 
VALUES ('kv', 'Komi');
INSERT INTO  Language 
VALUES ('kw', 'Cornish');
INSERT INTO  Language 
VALUES ('ky', 'Kirghiz');
INSERT INTO  Language 
VALUES ('la', 'Latin');
INSERT INTO  Language 
VALUES ('lb', 'Luxembourgish');
INSERT INTO  Language 
VALUES ('lg', 'Ganda');
INSERT INTO  Language 
VALUES ('li', 'Limburgan');
INSERT INTO  Language 
VALUES ('ln', 'Lingala');
INSERT INTO  Language 
VALUES ('lo', 'Lao');
INSERT INTO  Language 
VALUES ('lt', 'Lithuanian');
INSERT INTO  Language 
VALUES ('lu', 'Luba-Katanga');
INSERT INTO  Language 
VALUES ('lv', 'Latvian');
INSERT INTO  Language 
VALUES ('mg', 'Malagasy');
INSERT INTO  Language 
VALUES ('mh', 'Marshallese');
INSERT INTO  Language 
VALUES ('mi', 'Maori');
INSERT INTO  Language 
VALUES ('mk', 'Macedonian');
INSERT INTO  Language 
VALUES ('ml', 'Malayalam');
INSERT INTO  Language 
VALUES ('mn', 'Mongolian');
INSERT INTO  Language 
VALUES ('mr', 'Marathi');
INSERT INTO  Language 
VALUES ('ms', 'Malay');
INSERT INTO  Language 
VALUES ('mt', 'Maltese');
INSERT INTO  Language 
VALUES ('my', 'Burmese');
INSERT INTO  Language 
VALUES ('na', 'Nauru');
INSERT INTO  Language 
VALUES ('nb', 'Norwegian Bokmal');
INSERT INTO  Language 
VALUES ('nd', 'North Ndebele');
INSERT INTO  Language 
VALUES ('ne', 'Nepali');
INSERT INTO  Language 
VALUES ('ng', 'Ndonga');
INSERT INTO  Language 
VALUES ('nl', 'Dutch');
INSERT INTO  Language 
VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO  Language 
VALUES ('no', 'Norwegian');
INSERT INTO  Language 
VALUES ('nr', 'South Ndebele');
INSERT INTO  Language 
VALUES ('nv', 'Navajo');
INSERT INTO  Language 
VALUES ('ny', 'Chichewa');
INSERT INTO  Language 
VALUES ('oc', 'Occitan');
INSERT INTO  Language 
VALUES ('oj', 'Ojibwa');
INSERT INTO  Language 
VALUES ('om', 'Oromo');
INSERT INTO  Language 
VALUES ('or', 'Oriya');
INSERT INTO  Language 
VALUES ('os', 'Ossetian');
INSERT INTO  Language 
VALUES ('pa', 'Panjabi');
INSERT INTO  Language 
VALUES ('pi', 'Pali');
INSERT INTO  Language 
VALUES ('pl', 'Polish');
INSERT INTO  Language 
VALUES ('ps', 'Pushto');
INSERT INTO  Language 
VALUES ('pt', 'Portuguese');
INSERT INTO  Language 
VALUES ('qu', 'Quechua');
INSERT INTO  Language 
VALUES ('rm', 'Romansh');
INSERT INTO  Language 
VALUES ('rn', 'Rundi');
INSERT INTO  Language 
VALUES ('ro', 'Romanian');
INSERT INTO  Language 
VALUES ('ru', 'Russian');
INSERT INTO  Language 
VALUES ('rw', 'Kinyarwanda');
INSERT INTO  Language 
VALUES ('sa', 'Sanskrit');
INSERT INTO  Language 
VALUES ('sc', 'Sardinian');
INSERT INTO  Language 
VALUES ('sd', 'Sindhi');
INSERT INTO  Language 
VALUES ('se', 'Northern Sami');
INSERT INTO  Language 
VALUES ('sg', 'Sango');
INSERT INTO  Language 
VALUES ('si', 'Sinhala');
INSERT INTO  Language 
VALUES ('sk', 'Slovak');
INSERT INTO  Language 
VALUES ('sl', 'Slovenian');
INSERT INTO  Language 
VALUES ('sm', 'Samoan');
INSERT INTO  Language 
VALUES ('sn', 'Shona');
INSERT INTO  Language 
VALUES ('so', 'Somali');
INSERT INTO  Language 
VALUES ('sq', 'Albanian');
INSERT INTO  Language 
VALUES ('sr', 'Serbian');
INSERT INTO  Language 
VALUES ('ss', 'Swati');
INSERT INTO  Language 
VALUES ('st', 'Sotho');
INSERT INTO  Language 
VALUES ('su', 'Sundanese');
INSERT INTO  Language 
VALUES ('sv', 'Swedish');
INSERT INTO  Language 
VALUES ('sw', 'Swahili');
INSERT INTO  Language 
VALUES ('ta', 'Tamil');
INSERT INTO  Language 
VALUES ('te', 'Telugu');
INSERT INTO  Language 
VALUES ('tg', 'Tajik');
INSERT INTO  Language 
VALUES ('th', 'Thai');
INSERT INTO  Language 
VALUES ('ti', 'Tigrinya');
INSERT INTO  Language 
VALUES ('tk', 'Turkmen');
INSERT INTO  Language 
VALUES ('tl', 'Tagalog');
INSERT INTO  Language 
VALUES ('tn', 'Tswana');
INSERT INTO  Language 
VALUES ('to', 'Tonga');
INSERT INTO  Language 
VALUES ('tr', 'Turkish');
INSERT INTO  Language 
VALUES ('ts', 'Tsonga');
INSERT INTO  Language 
VALUES ('tt', 'Tatar');
INSERT INTO  Language 
VALUES ('tw', 'Twi');
INSERT INTO  Language 
VALUES ('ty', 'Tahitian');
INSERT INTO  Language 
VALUES ('ug', 'Uighur');
INSERT INTO  Language 
VALUES ('uk', 'Ukrainian');
INSERT INTO  Language 
VALUES ('ur', 'Urdu');
INSERT INTO  Language 
VALUES ('uz', 'Uzbek');
INSERT INTO  Language 
VALUES ('ve', 'Venda');
INSERT INTO  Language 
VALUES ('vi', 'Vietnamese');
INSERT INTO  Language 
VALUES ('vo', 'Volapuk');
INSERT INTO  Language 
VALUES ('wa', 'Walloon');
INSERT INTO  Language 
VALUES ('wo', 'Wolof');
INSERT INTO  Language 
VALUES ('xh', 'Xhosa');
INSERT INTO  Language 
VALUES ('yi', 'Yiddish');
INSERT INTO  Language 
VALUES ('yo', 'Yoruba');
INSERT INTO  Language 
VALUES ('za', 'Zhuang');
INSERT INTO  Language 
VALUES ('zh', 'Chinese');
INSERT INTO  Language 
VALUES ('zu', 'Zulu');
