SELECT * FROM Actor;
SELECT * FROM Country;
SELECT * FROM Director;
SELECT * FROM Directs;
SELECT * FROM Language;
SELECT * FROM Movie;
SELECT * FROM MovieTopics;
SELECT * FROM Topic;
SELECT * FROM Users;
